const SERVICE_CATALOG = {
  "Mobilya Montajı": [
    "Mobilya montajı",
    "Mobilya kurulumu",
    "Gardırop montajı",
    "Sürgülü gardırop montajı",
    "Dolap montajı",
    "Mutfak dolabı montajı",
    "Banyo dolabı montajı",
    "TV ünitesi montajı",
    "IKEA mobilya montajı",
    "Demonte mobilya montajı",
    "Mobilya demontajı",
    "Mobilya sökme",
    "Mobilya yeniden montajı",
    "Mobilya taşıma sonrası montajı",
    "Ofis mobilyası montajı",
    "Yatak odası mobilyası montajı",
    "Çocuk odası mobilyası montajı",
    "Bebek odası mobilyası montajı",
    "Kitaplık montajı",
    "Ayakkabılık montajı",
    "Portmanto montajı",
    "Konsol montajı",
    "Şifonyer montajı",
    "Komodin montajı",
    "Vitrin montajı",
    "Büfe montajı",
    "Makyaj masası montajı",
    "Çalışma masası montajı",
    "Bilgisayar masası montajı",
    "Ofis masası montajı",
    "Yemek masası montajı",
    "Sehpa montajı",
    "Ofis sandalyesi kurulumu",
    "Ranza montajı",
    "Karyola montajı",
    "Bebek yatağı montajı",
    "Baza montajı",
    "Yatak başlığı montajı",
    "Çocuk odası montajı",
    "Bebek odası montajı",
    "Dolap kapağı ayarı",
    "Dolap menteşesi değişimi",
    "Mobilya menteşe ayarı",
    "Çekmece rayı montajı",
    "Çekmece rayı değişimi",
    "Sürgülü dolap ayarı",
    "Sürgülü kapak ayarı",
    "Mobilya kapak değişimi",
    "Mobilya duvara sabitleme",
    "Dolap duvara sabitleme",
    "Gardırop duvara sabitleme",
    "Gardırop sabitleme",
    "Kitaplık duvara sabitleme",
    "Ağır raf montajı",
    "Mobilya ayak değişimi",
    "Mobilya tamiri"
  ],
  "TV • Raf • Duvar": [
    "TV montajı",
    "Televizyon duvara asma",
    "TV askı aparatı montajı",
    "TV ünitesi montajı",
    "TV sehpası kurulumu",
    "TV sehpası montajı",
    "TV kablo gizleme",
    "TV kablo kanalı montajı",
    "Soundbar montajı",
    "Soundbar duvar montajı",
    "Duvar rafı montajı",
    "Raf montajı",
    "Kitaplık montajı",
    "Ahşap raf montajı",
    "Metal raf montajı",
    "Mutfak rafı montajı",
    "Banyo rafı montajı",
    "Garaj rafı montajı",
    "Depo rafı montajı",
    "Duvar askısı montajı",
    "Askılık montajı",
    "Duvara eşya sabitleme",
    "Tablo asma",
    "Resim asma",
    "Saat montajı",
    "Ayna asma",
    "Dekoratif ayna montajı",
    "Duvar paneli montajı",
    "Dekoratif panel montajı",
    "Ahşap panel montajı",
    "Duvar çıtası montajı",
    "Modem duvar montajı",
    "Wi-Fi cihazı duvar montajı"
  ],
  "Perde • Korniş": [
    "Korniş montajı",
    "Perde montajı",
    "Stor perde montajı",
    "Zebra perde montajı",
    "Perde rayı montajı",
    "Perde rayı değişimi",
    "Korniş sökme",
    "Korniş değiştirme",
    "Korniş tamiri",
    "Çiftli korniş montajı",
    "Üçlü korniş montajı"
  ],
  "Elektrik • Aydınlatma": [
    "Avize montajı",
    "Avize takma",
    "Avize sökme",
    "Avize değiştirme",
    "Avize değişimi",
    "Aplik montajı",
    "Duvar lambası montajı",
    "Tavan lambası montajı",
    "LED lamba montajı",
    "LED plafonyer montajı",
    "Plafonyer montajı",
    "Sarkıt lamba montajı",
    "Spot lamba montajı",
    "Sensörlü lamba montajı",
    "Hareket sensörü montajı",
    "Bahçe aydınlatma montajı",
    "Dekoratif aydınlatma montajı",
    "LED şerit montajı",
    "Priz montajı",
    "Priz değişimi",
    "Elektrik anahtarı değişimi",
    "Anahtar montajı",
    "Anahtar değişimi",
    "Dimmer montajı",
    "USB priz montajı",
    "TV prizi montajı",
    "Data prizi montajı",
    "Kablo kanalı montajı",
    "Kablo kanalı döşeme",
    "Kablo gizleme",
    "Ethernet kablosu çekme",
    "İnternet kablosu döşeme",
    "Zayıf akım kablolama",
    "Elektrik kablosu çekme",
    "Aydınlatma hattı çekme",
    "Yeni priz hattı çekme",
    "Priz yeri değiştirme",
    "Anahtar yeri değiştirme",
    "Elektrik bağlantı kontrolü",
    "Basit elektrik arıza tespiti",
    "Sigorta değişimi",
    "Elektrik panosu kontrolü",
    "Fan montajı",
    "Banyo fanı montajı",
    "Aspiratör montajı",
    "Davlumbaz montajı",
    "Kapı zili montajı",
    "Kablosuz zil montajı",
    "Diafon montajı",
    "Sensör montajı",
    "Duman dedektörü montajı",
    "Akıllı kapı zili montajı"
  ],
  "Su Tesisatı • Banyo": [
    "Musluk montajı",
    "Musluk değişimi",
    "Mutfak bataryası montajı",
    "Banyo bataryası montajı",
    "Lavabo bataryası montajı",
    "Duş bataryası değişimi",
    "Duş seti montajı",
    "Duş seti değişimi",
    "Duş başlığı montajı",
    "Duş başlığı değişimi",
    "Taharet musluğu montajı",
    "Taharet musluğu değişimi",
    "Lavabo montajı",
    "Mutfak lavabo montajı",
    "Mutfak evye montajı",
    "Lavabo sifonu değişimi",
    "Sifon montajı",
    "Lavabo gideri değişimi",
    "Gider hortumu değişimi",
    "Gider bağlantısı",
    "Lavabo gider bağlantısı",
    "Mutfak gider bağlantısı",
    "Banyo gider bağlantısı",
    "Çamaşır makinesi gider bağlantısı",
    "Bulaşık makinesi gider bağlantısı",
    "Çamaşır makinesi su bağlantısı",
    "Bulaşık makinesi su bağlantısı",
    "Su hortumu değişimi",
    "Flexible hortum değişimi",
    "Vana değişimi",
    "Ara musluk değişimi",
    "Klozet rezervuar bağlantısı",
    "Rezervuar iç takım değişimi",
    "Rezervuar tamiri",
    "Klozet kapağı montajı",
    "Klozet aksesuar montajı",
    "Banyo aksesuar montajı",
    "Havluluk montajı",
    "Tuvalet kağıtlığı montajı",
    "Sabunluk montajı",
    "Diş fırçalık montajı",
    "Banyo askılığı montajı",
    "Duşakabin aksesuar montajı",
    "Duşakabin silikon yenileme",
    "Duşakabin kapak ayarı",
    "Duşakabin montajı",
    "Lavabo dolabı montajı",
    "Banyo dolabı montajı",
    "Su tesisatı küçük tamiratı",
    "Su arıtma montajı"
  ],
  "Beyaz Eşya • Ankastre": [
    "Çamaşır makinesi kurulumu",
    "Çamaşır makinesi montajı",
    "Çamaşır makinesi hortum bağlantısı",
    "Çamaşır makinesi yer değiştirme",
    "Bulaşık makinesi kurulumu",
    "Bulaşık makinesi montajı",
    "Bulaşık makinesi hortum bağlantısı",
    "Bulaşık makinesi yer değiştirme",
    "Buzdolabı kurulumu",
    "Ankastre fırın montajı",
    "Ankastre ocak montajı",
    "Davlumbaz montajı",
    "Aspiratör montajı",
    "Ankastre davlumbaz montajı",
    "Ankastre cihaz montajı",
    "Beyaz eşya sökme",
    "Beyaz eşya yeniden kurulum"
  ],
  "Ayna • Banyo Aksesuarları": [
    "Ayna montajı",
    "Banyo aynası montajı",
    "Banyo dolabı montajı",
    "Lavabo dolabı montajı",
    "Banyo rafı montajı",
    "Havluluk montajı",
    "Tuvalet kağıtlığı montajı",
    "Duşakabin aksesuar montajı",
    "Duş başlığı montajı",
    "Duş seti montajı",
    "Sabunluk montajı",
    "Diş fırçalık montajı",
    "Banyo askılığı montajı",
    "Klozet kapağı montajı",
    "Klozet aksesuar montajı"
  ],
  "Kapı • Pencere": [
    "Kapı kolu değişimi",
    "Kapı kolu montajı",
    "Kapı stoperi montajı",
    "Kapı tamponu montajı",
    "Kapı menteşesi değişimi",
    "Kapı menteşesi ayarı",
    "Kapı kilidi değişimi",
    "Kapı kilit karşılığı ayarı",
    "Kapı altı süpürgelik montajı",
    "Pencere kolu değişimi",
    "Pencere kolu montajı",
    "Pimapen kolu değişimi",
    "Pimapen kolu montajı",
    "Pimapen ayarı",
    "Pencere stoperi montajı"
  ],
  "Ev • Handyman • Tamirat": [
    "Ev tamiratı",
    "Küçük ev tamiratı",
    "Ev içi montaj işleri",
    "Genel montaj hizmeti",
    "Handyman hizmeti",
    "Evde montaj hizmeti",
    "Evde küçük tamirat",
    "Ev bakım hizmeti",
    "Taşınma sonrası montaj",
    "Yeni eve montaj",
    "Yeni eve montaj hizmeti",
    "Kiracı çıkış tamiratı",
    "Ev sahibi küçük tamiratları",
    "Duvara eşya montajı",
    "Duvara sabitleme",
    "Mobilya sabitleme",
    "Deprem güvenliği için mobilya sabitleme",
    "Montaj ve demontaj hizmeti",
    "Sökme takma hizmeti",
    "Ev aksesuar montajı",
    "Duvar aksesuarı montajı",
    "Teknik montaj hizmeti",
    "Ev teknik servis",
    "Ev montaj ustası",
    "Mobilya montaj ustası",
    "Montaj ustası",
    "Teknik montaj",
    "Ev montaj işleri",
    "Küçük tamirat işleri",
    "Ev tamir işleri",
    "Sökme takma işleri",
    "Ev bakım ve onarım",
    "Genel handyman hizmeti",
    "Süpürgelik montajı",
    "Parke döşeme",
    "Parke süpürgelik montajı",
    "Duvar tamiratı",
    "Alçıpan tamiratı",
    "Derz yenileme",
    "Boya öncesi tamirat",
    "Teras su yalıtımı"
  ],
  "Ev • Güvenlik • Teknoloji": [
    "Bebek kamerası montajı",
    "Güvenlik kamerası montajı",
    "Diafon montajı",
    "Kapı zili montajı",
    "Kablosuz zil montajı",
    "Sensör montajı",
    "Duman dedektörü montajı",
    "Wi-Fi cihazı duvar montajı",
    "Modem duvar montajı",
    "Araç içi kamera montajı",
    "Spor aletleri montajı"
  ],
  "Mutfak • Niş Montajlar": [
    "Kahve köşesi montajı",
    "Çamaşır makinesi dolabı montajı",
    "Fırın dolabı montajı",
    "Mikrodalga rafı montajı",
    "Baharatlık montajı",
    "Çöp kovası mekanizması montajı",
    "Mutfak aksesuar montajı",
    "Dolap içi aksesuar montajı",
    "Çekmece düzenleyici montajı",
    "Pantolon askılığı montajı",
    "Dolap içi LED montajı",
    "Gardırop LED montajı",
    "Mutfak LED montajı",
    "Banyo LED montajı"
  ],
  "IKEA • Genel": [
    "IKEA mobilya montajı",
    "IKEA mobilya kurulum hizmeti",
    "IKEA mobilya sökme hizmeti",
    "IKEA mobilya yeniden kurulum",
    "IKEA mobilya duvara sabitleme",
    "IKEA mobilya ayak montajı",
    "IKEA mobilya kapak ayarı",
    "IKEA mobilya menteşe ayarı",
    "IKEA mobilya çekmece ayarı",
    "IKEA mobilya raf montajı",
    "IKEA duvar rafı montajı",
    "IKEA TV ünitesi montajı",
    "IKEA kitaplık montajı",
    "IKEA gardırop montajı",
    "IKEA çocuk odası montajı",
    "IKEA bebek mobilyası montajı",
    "IKEA antre mobilyası montajı"
  ],
  "IKEA • PAX": [
    "IKEA PAX gardırop montajı",
    "IKEA PAX kapak montajı",
    "IKEA PAX sürgülü kapak montajı",
    "IKEA PAX menteşe ayarı",
    "IKEA PAX KOMPLEMENT montajı",
    "IKEA PAX iç düzenleyici montajı",
    "IKEA PAX çekmece montajı",
    "IKEA PAX raf montajı",
    "IKEA PAX askı aparatı montajı",
    "IKEA PAX gardırop sabitleme",
    "IKEA PAX sökme ve yeniden kurma"
  ],
  "IKEA • KALLAX": [
    "IKEA KALLAX montajı",
    "IKEA KALLAX raf montajı",
    "IKEA KALLAX kapak montajı",
    "IKEA KALLAX çekmece montajı",
    "IKEA KALLAX sepet montajı",
    "IKEA KALLAX ayak montajı",
    "IKEA KALLAX duvara sabitleme",
    "IKEA KALLAX bölme montajı",
    "IKEA KALLAX sökme ve yeniden kurma"
  ],
  "IKEA • BESTÅ / BILLY / EKET": [
    "IKEA BESTÅ montajı",
    "IKEA BESTÅ TV ünitesi montajı",
    "IKEA BESTÅ duvar montajı",
    "IKEA BESTÅ kapak montajı",
    "IKEA BESTÅ çekmece montajı",
    "IKEA BESTÅ ayak montajı",
    "IKEA BILLY montajı",
    "IKEA BILLY kitaplık montajı",
    "IKEA BILLY kitaplık duvara sabitleme",
    "IKEA BILLY kapak montajı",
    "IKEA EKET montajı",
    "IKEA EKET dolap montajı",
    "IKEA EKET duvar montajı",
    "IKEA EKET raf montajı"
  ],
  "IKEA • MALM / HEMNES / BRIMNES": [
    "IKEA MALM montajı",
    "IKEA MALM yatak montajı",
    "IKEA HEMNES montajı",
    "IKEA HEMNES yatak montajı",
    "IKEA BRIMNES montajı",
    "IKEA BRIMNES yatak montajı",
    "IKEA şifonyer montajı",
    "IKEA komodin montajı"
  ],
  "IKEA • PLATSA / METOD / ENHET": [
    "IKEA PLATSA montajı",
    "IKEA METOD montajı",
    "IKEA METOD mutfak montajı",
    "IKEA METOD mutfak dolabı montajı",
    "IKEA METOD üst dolap montajı",
    "IKEA METOD alt dolap montajı",
    "IKEA ENHET montajı",
    "IKEA ENHET dolap montajı",
    "IKEA ENHET banyo dolabı montajı",
    "IKEA mutfak dolabı montajı",
    "IKEA tezgah montajı",
    "IKEA mutfak çekmecesi montajı"
  ],
  "IKEA • Masa / Çalışma Alanı": [
    "IKEA MICKE montajı",
    "IKEA MICKE çalışma masası montajı",
    "IKEA ALEX montajı",
    "IKEA ALEX çekmeceli ünite montajı",
    "IKEA LAGKAPTEN montajı",
    "IKEA LAGKAPTEN masa montajı",
    "IKEA LINNMON montajı",
    "IKEA LINNMON masa montajı",
    "IKEA IDÅSEN montajı",
    "IKEA IDÅSEN masa montajı",
    "IKEA BEKANT montajı",
    "IKEA BEKANT masa montajı",
    "IKEA çalışma masası montajı",
    "IKEA bilgisayar masası montajı"
  ],
  "IKEA • Diğer Modeller": [
    "IKEA EKET montajı",
    "IKEA IVAR montajı",
    "IKEA TROFAST montajı",
    "IKEA SMÅSTAD montajı",
    "IKEA FAKTUM montajı",
    "IKEA VITTSJÖ montajı",
    "IKEA LACK montajı",
    "IKEA FJÄLLBO montajı",
    "IKEA RÅVAROR montajı",
    "IKEA HAUGA montajı",
    "IKEA SONGESAND montajı",
    "IKEA KULLEN montajı",
    "IKEA TARVA montajı",
    "IKEA NORDLI montajı",
    "IKEA TYSSEDAL montajı",
    "IKEA SLÄKT montajı",
    "IKEA SLÄKT yatak montajı",
    "IKEA SUNDVIK montajı",
    "IKEA MINNEN montajı",
    "IKEA SNIGLAR montajı",
    "IKEA karyola montajı",
    "IKEA baza montajı"
  ]
};
